### ISSUE TITLE
Incorrect time on Safari browser

### ISSUE THREAD

**Issue by n34l** [PublicHealthEngland/coronavirus-dashboard#10]
<img width="879" alt="Chrome time (correct)" src="https://user-images.githubusercontent.com/58686094/78803074-77d9e980-79b6-11ea-9da0-e0b7cc3f8c00.png">
<img width="631" alt="Safari time (incorrect)" src="https://user-images.githubusercontent.com/58686094/78803087-7b6d7080-79b6-11ea-898d-eb00eeb6c276.png">

Safari shows incorrect last updated time.
Shows correct time on Chrome, Firefox etc.

**Comment by xenatisch** [comment]
The preceeding commit only swaps the issue. Now FF is an hour ahead of Safari.
 
This issue is due to the missing "Z" in the source file, which violates the ISO standard protocol. 

Awaiting additional instructions on how to address the issue.

**Comment by n34l** [comment]
Issue resolved.
