### ISSUE TITLE
Archive page throws error in Firefox

### ISSUE THREAD

**Issue by dracos** [PublicHealthEngland/coronavirus-dashboard#124]
The intro text shows but it says "Loading..." and no table appears.
The console error is "WrongDocumentError: Node cannot be used in a document other than the one in which it was created"

**Comment by xenatisch** [comment]
It happens on all browsers. The `/downloads/` prepend is missing from the paths. It's been fixed in (https://github.com/PublicHealthEngland/coronavirus-dashboard/commit/6dea11239a91966ff8efa43765cdef5b9cf62cad)[this commit], which will be deployed to the service in the next release, possibly in the next hour or so.

**Comment by dracos** [comment]
It's fine in Chrome? Perhaps I wasn't clear, I'm not talking about the downloads, but the page itself.

Chrome:
![image](https://user-images.githubusercontent.com/154364/80747829-ec1e2d80-8b1b-11ea-8337-8de821480050.png)

Firefox:
![image](https://user-images.githubusercontent.com/154364/80747857-f9d3b300-8b1b-11ea-9ce7-84d088e74395.png)

**Comment by dracos** [comment]
I don't see what difference the URL to the downloads makes to this bug report, which is about the display of the whole table in Firefox. For now, anyone else with this issue can use the static HTML version at http://www.dracos.co.uk/made/coronavirus.data.gov.uk/archive/ which avoids JavaScript issues in Firefox, IE11, or anything else.

**Comment by xenatisch** [comment]
Oh right. This is another issue. We have a URL issue too. Sorry, I thought it was that one.

**Comment by xenatisch** [comment]
Ok, it's now fixed. I'll create a release and dispatch it with some other stuff tomorrow. It's not a high priority fix as it's not a primary feature and only 3.09% of users use Firefox.
