### ISSUE TITLE
Replacement for the “pythonic” package in the frontend to address IE issues

### ISSUE THREAD

**Issue by bsaadat** [PublicHealthEngland/coronavirus-dashboard#128]

**Comment by xenatisch** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Replacement for the “pythonic” package in the frontend to address IE issues](https://trello.com/c/fyrSvVoH/349-replacement-for-the-pythonic-package-in-the-frontend-to-address-ie-issues)

**Comment by xenatisch** [comment]
The next release will include a fix for this issue.
