### ISSUE TITLE
Total number of lab-confirmed cases in England by age and sex as CSV

### ISSUE THREAD

**Issue by robchallen** [PublicHealthEngland/coronavirus-dashboard#129]
It would be great if we could access all the data on the page as a timeseries :-) I'm particularly interested in the numbers driving this age / sex breakdown table, and how they have changed over time.

Alternatively, maybe there is an open API to the data you could direct me to?

**Comment by robchallen** [comment]
N.B. I found the data file at:

https://c19downloads.azureedge.net/downloads/data/data_latest.json

which more or less meets my needs for today but I can't work out if there is an archive with previous days data.

**Comment by Ha-san-ali** [comment]
Hi @robchallen We don't have a formal Open API, at least not yet, although potentially something we will create in the future. You can find an archive here https://coronavirus.data.gov.uk/archive

**Comment by xenatisch** [comment]
@robchallen The data file is not a public asset. It is subject to change without prior notice.

Also, we don't currently have any plans to release the age / sex data as time series, but you're welcome to submit a request through the email. We will, however, be incorporating the existing data into our public JSON files in the near future.
