### ISSUE TITLE
Bug: line charts reversed after toggle to table

### ISSUE THREAD

**Issue by bsaadat** [PublicHealthEngland/coronavirus-dashboard#131]
**Summary of issue**
If I use the radio button to change from Chart to Table, and then back to Chart, the line chart's X axis are then reversed! 

**Steps to reproduce**
Scroll down to charts
Select table radio button
Select chart radio button

**Expected result**
Charts appear as before

**Actual result**
Line chart x axis is reversed

**System**
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36 Edg/81.0.416.68

**Comment by Ha-san-ali** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug: line charts reversed after toggle to table](https://trello.com/c/ihPIrJqc/364-bug-line-charts-reversed-after-toggle-to-table)
