### ISSUE TITLE
Bug: Chart data is distorted after switching between chart view and toggle view

### ISSUE THREAD

**Issue by bsaadat** [PublicHealthEngland/coronavirus-dashboard#132]
**Summary of issue**
If you then use the toggle further up the page to view the data as a table, and then switch it back to a chart again, the data on this chart changes. The new chart appears to incorrectly suggest that a substantial amount of new cases were detected at the end of January in England. The new chart displayed is shown below:

**Steps to reproduce**
toggle from chart view to table view back to chart view

**Expected result**
Charts remain as nromal

**Actual result**
Bar charts add new cases to the wrong date

**System**

**Comment by Ha-san-ali** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug: line charts reversed after toggle to table](https://trello.com/c/ihPIrJqc/364-bug-line-charts-reversed-after-toggle-to-table)

**Comment by Ha-san-ali** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug: Chart data is distorted after switching between chart view and toggle view](https://trello.com/c/9JVLMIzB/365-bug-chart-data-is-distorted-after-switching-between-chart-view-and-toggle-view)
