### ISSUE TITLE
Reduce text size on axis labels for graphs on MOBILE to 12px to fix overcrowding.

### ISSUE THREAD

**Issue by bsaadat** [PublicHealthEngland/coronavirus-dashboard#134]
**Description**
We recently increased the text on the axis labels and tooltips to 14px, this is great for desktop users but has made the mobile experience works

We should change the font for graph axis labels to 12px **on mobile only** to fix this. see image of the current problem

**Acceptance criteria**
Graph axis labels on mobile are not overcrowded and hard to read

**Comment by Ha-san-ali** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Reduce text size on axis labels for graphs on MOBILE to 12px to fix overcrowding.](https://trello.com/c/ZdTGVdqr/361-reduce-text-size-on-axis-labels-for-graphs-on-mobile-to-12px-to-fix-overcrowding)
