### ISSUE TITLE
Chart colours are too similar

### ISSUE THREAD

**Issue by acme** [PublicHealthEngland/coronavirus-dashboard#145]
The chart colours are both "dark blue" and are hard to distinguish:

<img width="729" alt="image" src="https://user-images.githubusercontent.com/19988/80923117-68fa1300-8d79-11ea-88ab-28d4bc5d53e3.png">

Perhaps we could increase the contrast or use the colour palette in the [GOV.UK Design System](https://design-system.service.gov.uk/styles/colour/)?

**Comment by xenatisch** [comment]
@acme Yeah... It's in the backlog and my to do list. Thanks though.

**Comment by xenatisch** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve colour palette to better distinguish data on graphs](https://trello.com/c/Z3J2zRDm/334-improve-colour-palette-to-better-distinguish-data-on-graphs)
