### ISSUE TITLE
Incorrect Order of Deaths 

### ISSUE THREAD

**Issue by przemyslawpluta** [PublicHealthEngland/coronavirus-dashboard#154]
At the moment it appears that dash reports only hospital daily deaths **315**

<img width="1089" alt="ref" src="https://user-images.githubusercontent.com/221250/80960032-ed8f7480-8dff-11ea-838c-fe2cbbf4679d.png">

Instead of deaths in **all settings** as reported by [gov.uk](https://www.gov.uk/guidance/coronavirus-covid-19-information-for-the-public) 

<img width="666" alt="govuk" src="https://user-images.githubusercontent.com/221250/80960152-36472d80-8e00-11ea-86a0-955e751ec018.png">

Additionally it looks like numbers on the **GOV.UK** site are incorrect for daily deaths essentially it should be **Deaths in hospitals** at **315** with **Deaths in all settings** at **396** as **Deaths in all settings** should already include deaths in hospitals already.

**Comment by xenatisch** [comment]
@przemyslawpluta This is not a development issue, I'm afraid. We do not handle the data pipeline. 

Please read the [About the data](https://coronavirus.data.gov.uk/about) section of the website where the reason for these inconsistencies are explained.

For additional questions and requests, please get in touch using the email provided in the footer of the website.
