### ISSUE TITLE
Page is blank in desktop Safari (throws a WebGL error)

### ISSUE THREAD

**Issue by frankieroberto** [PublicHealthEngland/coronavirus-dashboard#16]
Currently in desktop Safari, for me at least, the page renders but then very quickly (less than a second) switches to a white blank screen.

Developer console shows that a WebGL exception is being thrown:

<img width="1119" alt="Screenshot 2020-04-15 at 11 35 26" src="https://user-images.githubusercontent.com/30665/79327979-3fce2b80-7f0d-11ea-836c-ef21be01a626.png">

**Comment by xenatisch** [comment]
Is this resolved?

**Comment by frankieroberto** [comment]
@xenatisch nope, I'm getting the same issues. Safari version 13.0.5 on Mac. Works in Chrome though, and mobile Safari.

**Comment by xenatisch** [comment]
That's really bizarre.

<img width="1322" alt="Screenshot 2020-04-15 at 23 44 31" src="https://user-images.githubusercontent.com/13240654/79396185-3c6d8b00-7f73-11ea-98c2-918a7eae001b.png">

The service has been tested on both Mac and Safari.

Could you by any chance clear your cache and try again?

**Comment by frankieroberto** [comment]
@xenatisch I've cleared the cache, but it's the same error. I think it's because WebGL isn't enabled/working in my version of Safari for some reason (and I can't see how to turn it on!), as https://get.webgl.org doesn't load either.

It's probably worth detecting whether WebGL is available, and then only displaying those features (the map?) if it is.

**Comment by xenatisch** [comment]
Can you make your browser smaller so that it'll show the mobile view instead? The map is not shown in mobile view, so it should work.

**Comment by frankieroberto** [comment]
@xenatisch yeah, it works if I reload the page with a mobile-width sized browser.

I don't see the "Allow WebGL" checkbox – I think that was removed from Safari at some point (and it's always enabled). No idea why it's not working for me though... 🤷 

If I load the [example on the Mapbox website](https://docs.mapbox.com/mapbox-gl-js/example/simple-map/) it displays an error:

<img width="629" alt="Screenshot 2020-04-16 at 14 17 50" src="https://user-images.githubusercontent.com/30665/79460751-28ff0600-7fed-11ea-944d-3f3d57ff346c.png">

so perhaps it's possible to detect WebGL and have a more graceful fallback (eg just showing the rest of the page)?

Thanks!

**Comment by xenatisch** [comment]
> so perhaps it's possible to detect WebGL and have a more graceful fallback (eg just showing the rest of the page)?

It is possible, yeah. In fact, it's fairly easy. What you want is first to see if it exists on the browser (i.e. look for `window.WebGLRenderingContext`), and if it does, whether it is enabled. The latter is a bit more tricky, because you need to test it differently for different browsers, but it is easily doable. 

Any thoughts on this, @danielflint ?

**Comment by xenatisch** [comment]
@frankieroberto We have now added this to our backlog for a review.

**Comment by EdwardBetts** [comment]
I had the same problem with Firefox on Linux. The page appeared blank because WebGL was broken in my browser. I fixed WebGL and now the page displays correctly. It would be great if the dashboard could show the numbers even if WebGL is not working.

**Comment by Ha-san-ali** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fail gracefully for WebGL error](https://trello.com/c/Pbn4OsUf/242-fail-gracefully-for-webgl-error)

**Comment by xenatisch** [comment]
@EdwardBetts, @frankieroberto 

The new update to the website - once deployed - would solve this issue.

**Comment by frankieroberto** [comment]
@xenatisch works for me, thanks! Now I can view the page in Safari (I’ve still not worked out why WebGL is broken or disabled in Safari for me).

**Comment by xenatisch** [comment]
@frankieroberto Well, it was a contribution by @TomFryers, so the credit should go to him. I never really found the time to do it, even though it had been sitting in my backlog for about 10 days. 

Re the issue, I honestly have no idea why it's happening... Funny thing is, there's no option to disable it either, so to test the fix, I had the return `false` values from the function that verifies the presence of WebGL. 

I know at least 4 other people have reported the issue, all of them in Safari. I'm starting to think that it might actually be bug of some sort. May be worth reporting it to Apple.
