### ISSUE TITLE
"Rate" terminology in table of cases in each region is confusing

### ISSUE THREAD

**Issue by ianhinder** [PublicHealthEngland/coronavirus-dashboard#167]
The page does not explain what "rate" means in the table of cases in each region.  The table comes below the first section which compares total cases vs daily cases.  One might expect the following table to do the same, and "rate" can be interpreted as the number of new cases per day (I interpreted it like this initially, until I investigated and found the definition of "rate" in the "About the data" tab). I propose that there should be something in this table similar to that in the adjacent map such as "per 100,000 resident population" to make it clear that rate does not mean "new cases per day".

**Comment by xenatisch** [comment]
@ianhinder Once again, thank you for getting in touch, but I am afraid this is not a development issue either.

This is related to out data team + the team that is in charge of user testing. 

Please get in touch using the email address provided in the footer of the website to express your suggestions and requests. I assure you that every single email is read and actioned appropriately.
