### ISSUE TITLE
Inconsistency between headline daily case count and table of daily cases should be clarified

### ISSUE THREAD

**Issue by ianhinder** [PublicHealthEngland/coronavirus-dashboard#168]
The "Daily number of lab-confirmed UK cases" on 14-May-2020 is 3446.  The "Daily number of lab-confirmed cases in England by specimen date" for 09-May-2020 is 879 (I go back 5 days because the current number is expected to be incomplete).  There is a vast difference between these two numbers, not attributable to the 5 day lag.  The explanation that I can find in the "About the data" tab is that the headline figure contains both Pillar 1 and Pillar 2 cases, whereas the table by specimen data contains only Pillar 1 cases.  This should be made clear, to emphasise that the numbers depend strongly on which cases are included.  It would also be helpful to have data on the number of Pillar 1  tests carried out by specimen date, to see if the drop in Pillar 1 cases is attributable just to a transfer of testing from Pillar 1 to Pillar 2 (for example).

**Comment by xenatisch** [comment]
@ianhinder Thank you for getting in touch. I am afraid this is not a development issue. We cannot alter the labels / descriptions without explicit authorisation. Please get in touch using the email address provided in the footer of the website to express your suggestions and requests.
