### ISSUE TITLE
Publish Pillar 2 case data at local authority level

### ISSUE THREAD

**Issue by rcatlord** [publichealthengland/coronavirus-dashboard#199]
With Pillar 2 tests accounting for a larger share of new confirmed cases of coronavirus (see recent [FT article](https://www.ft.com/content/301c847c-a317-4950-a75b-8e66933d423a)) can they be published alongside Pillar 1 data at local authority level?

**Comment by xenatisch** [comment]
@rcatlord, thank you for getting in touch. This issue is not related to the development of the platform. Please direct your requests, queries and suggestions to the email provided on the website so that it will be forwarded to the relevant team.

**Comment by rcatlord** [comment]
It seems that daily confirmed new cases tested under pillar 1 and pillar 2 programmes are now available by local authority on the [coronavirus dashboard](https://coronavirus.data.gov.uk/#category=nations&map=rate). Thank you.
