### ISSUE TITLE
New Dashboard Incorrect Data for Scotland

### ISSUE THREAD

**Issue by przemyslawpluta** [publichealthengland/coronavirus-dashboard#203]
It appears that cases for [Scotland](https://coronavirus-staging.data.gov.uk/cases?areaType=nation&areaName=Scotland) in new dashboard are incorrect and pre-filled for entire year [query](https://api.coronavirus-staging.data.gov.uk/v1/data?filters=areaType=nation;areaName=Scotland&structure=%7B%22areaType%22:%22areaType%22,%22areaName%22:%22areaName%22,%22areaCode%22:%22areaCode%22,%22date%22:%22date%22,%22newCasesBySpecimenDate%22:%22newCasesBySpecimenDate%22,%22cumCasesBySpecimenDate%22:%22cumCasesBySpecimenDate%22%7D&format=json)

![sco-daily](https://user-images.githubusercontent.com/221250/88787907-81b57180-d18c-11ea-8cf3-00b42e371f54.jpg)
![sco-cumulative](https://user-images.githubusercontent.com/221250/88787918-8417cb80-d18c-11ea-81c9-a691b831fe6a.jpg)
![sco-data](https://user-images.githubusercontent.com/221250/88787929-8aa64300-d18c-11ea-81a0-a7f561895c20.jpg)

**Comment by xenatisch** [comment]
@przemyslawpluta The data formats were changed in our feed without prior notice, causing our pipeline to break. Our data team are working to fix the issue as soon as possible. 

Apologies for the inconvenience.
