### ISSUE TITLE
New Dashboard Incorrect Future Date in Daily cases by date reported for England, Wales

### ISSUE THREAD

**Issue by przemyslawpluta** [publichealthengland/coronavirus-dashboard#204]
Daily cases by date reported for England, Wales seems to have a date `07-12-2020` in the future in timeseries for [England](https://api.coronavirus-staging.data.gov.uk/v1/data?filters=areaType=nation;areaName=England&structure=%7B%22areaType%22:%22areaType%22,%22areaName%22:%22areaName%22,%22areaCode%22:%22areaCode%22,%22date%22:%22date%22,%22newCasesByPublishDate%22:%22newCasesByPublishDate%22,%22cumCasesByPublishDate%22:%22cumCasesByPublishDate%22%7D&format=json) [Wales](https://api.coronavirus-staging.data.gov.uk/v1/data?filters=areaType=nation;areaName=Wales&structure=%7B%22areaType%22:%22areaType%22,%22areaName%22:%22areaName%22,%22areaCode%22:%22areaCode%22,%22date%22:%22date%22,%22newCasesByPublishDate%22:%22newCasesByPublishDate%22,%22cumCasesByPublishDate%22:%22cumCasesByPublishDate%22%7D&format=json)

![wal](https://user-images.githubusercontent.com/221250/88788763-b2e27180-d18d-11ea-89b7-501b6d067a32.jpg)
![eng](https://user-images.githubusercontent.com/221250/88788765-b4ac3500-d18d-11ea-8cc8-7ea9aeeb1266.jpg)

**Comment by xenatisch** [comment]
Same issue as #203.
