### ISSUE TITLE
New Dashboard Include Cumulative Tests Either Processed or Sent Out

### ISSUE THREAD

**Issue by przemyslawpluta** [publichealthengland/coronavirus-dashboard#205]
New Dashboard does not seems to include a number for `Cumulative Tests Either Processed or Sent Out` as reported by [gov.uk](https://www.gov.uk/guidance/coronavirus-covid-19-information-for-the-public)

<img width="686" alt="tests" src="https://user-images.githubusercontent.com/221250/88890507-a156a380-d239-11ea-8384-7d0ffbdc5670.png">

<img width="782" alt="nd" src="https://user-images.githubusercontent.com/221250/88890625-cb0fca80-d239-11ea-9257-3bb32c44bff0.png">

**Comment by xenatisch** [comment]
@przemyslawpluta That is correct - the dashboard only displays the number of "tests processed", not those that have been made available or just sent out but not returned or processed.
