### ISSUE TITLE
Explain the charts

### ISSUE THREAD

**Issue by acme** [PublicHealthEngland/coronavirus-dashboard#21]
Thanks for the dashboard, but I think the charts need a little explanation.

I've seen many people take the drop in numbers for the last few days in the "Daily number of lab-confirmed cases in England by specimen date" chart as proof that the pandemic is over:

<img width="530" alt="image" src="https://user-images.githubusercontent.com/19988/79422219-66936d00-7fb4-11ea-8245-1fb53ff2797f.png">

That's not the case. Instead, the reason is presumably that there is a reporting lag. Perhaps the last few days could be marked as having incomplete data?

There's also a weekly variation in the charts, presumably due to increased lag on weekends. Perhaps weekends could be highlighted on the charts?

I feel the [Financial Times Coronavirus tracker](https://www.ft.com/coronavirus-latest) does a great job on explaining the charts, for example using a 7-day rolling average to address reporting lag.

**Comment by xenatisch** [comment]
@acme Thank you getting in touch. We have noticed and raised the issue with the relevant team to investigate. 

Please feel free to get in touch via the email at the footer of the page to reiterate the problem.

**Comment by KevinMayfield** [comment]
This appears to be a duplicate https://github.com/PublicHealthEngland/coronavirus-dashboard/issues/35

It appears you are reporting by specimen date not pathology report date. E.g. figure above for 14/Apr is around 100, on the current dashboard it is now 2998. A time lag of between test orders and path reports of around 48 hours appears to explain the difference. 

How is the total new cases being calculated? This doesn't appear to match above (but could be using pathology report date - same as welsh and scottish covid sites)

**Comment by Ha-san-ali** [comment]
@paulfryers

**Comment by Ha-san-ali** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Users confused by UK total and latest cases](https://trello.com/c/RJgqfiEl/266-users-confused-by-uk-total-and-latest-cases)

**Comment by annapowellsmith** [comment]
@KevinMayfield see my comment on #35. I would also like to understand how this affects the UK daily total.

**Comment by xenatisch** [comment]
Release of [version 1.0.11](https://github.com/PublicHealthEngland/coronavirus-dashboard/releases/tag/1.0.11) should solve this issue. The release is now deployed on the website, and provides additional description to the figures displayed.

**Comment by KevinMayfield** [comment]
Not sure if cases is the correct term here. The specimen date is often going to match when the test was ordered. 
I think people are expecting the date of when the diagnostic report result was made.

Not sure if you have this, I can't see details of SGSS input format but would expect the text file it mentions to be HL7v2, ASTM or EDIFACT - so would presume it is present.

**Comment by xenatisch** [comment]
@Ha-san-ali, could you please look into @KevinMayfield's comment?

**Comment by acme** [comment]
Thanks, the description in "About the data" is clear, however it is very separate to the charts.

**Comment by Ha-san-ali** [comment]
Yes @acme you are right we are working on fixing that.

**Comment by Ha-san-ali** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Feature: Split bars for daily cases into "previously reported" and "newly reported"](https://trello.com/c/jSycavkQ/268-feature-split-bars-for-daily-cases-into-previously-reported-and-newly-reported)

**Comment by Ha-san-ali** [comment]
@acme This has been addressed in the latest release. The graph is now a stacked bar chart that discerns between previously reported and newly reported cases. You can also select the legend to filter the graph.

**Comment by acme** [comment]
Thanks, looks great.
