### ISSUE TITLE
Can't retrieve newPillarFourTestsByPublishDate metric via API

### ISSUE THREAD

**Issue by paulmaunders** [publichealthengland/coronavirus-dashboard#228]
I am able to retrieve daily test data for Pilar 1, 2 and 3 from the API - but when I try to query Pilar 4 data it returns `HTTP/1.1 204 No Content`. 

* newPillarOneTestsByPublishDate - OK
* newPillarTwoTestsByPublishDate - OK 
* newPillarThreeTestsByPublishDate - OK 
* newPillarFourTestsByPublishDate - FAILS

Example of Pilar 3 working:

```
 % curl -si 'https://api.coronavirus-staging.data.gov.uk/v1/data?filters=areaName=England&structure=%7B%22date%22:%22date%22,%22PillarThreeTests%22:%22newPillarThreeTestsByPublishDate%22%7D'
HTTP/1.1 200 OK
```

Example of Pilar 4 returning empty:

```
% curl -si 'https://api.coronavirus-staging.data.gov.uk/v1/data?filters=areaName=England&structure=%7B%22date%22:%22date%22,%22PillarFourTests%22:%22newPillarFourTestsByPublishDate%22%7D'
HTTP/1.1 204 No Content
```

**Comment by xenatisch** [comment]
Hi @paulmaunders 

Thanks for getting in touch. 

I don't think we ever really had the Pillar 4 testing figures for England - I think they are only published at UK level. I'll ask the data team again, but I'm fairly sure.

**Comment by statsgeekclare** [comment]
Hi @paulmaunders 

We don't have Pillar 4 data separated out by country, it's a UK-only series. 

Test and Trace may have more information, we are dependent on what we receive from them to drop into the dashboard.

**Comment by paulmaunders** [comment]
No problem, thanks for clarifying!
