### ISSUE TITLE
Selecting Chart / Table radio buttons changes daily deaths to 14

### ISSUE THREAD

**Issue by xenatisch** [PublicHealthEngland/coronavirus-dashboard#23]
To reproduce, do as follows:

1.  Click Table radio button
2. Click Chart radio button
3. Daily deaths value changes to 14

![image](https://user-images.githubusercontent.com/13240654/79444277-e6303480-7fd2-11ea-9d1c-ec5b06caba50.png)

**Comment by n34l** [comment]
issue solved
