### ISSUE TITLE
Download of data from "Patients admitted to hospital, by age" and "Admission rates by age" doesn't work

### ISSUE THREAD

**Issue by theosanderson** [publichealthengland/coronavirus-dashboard#238]
The JSON/XML links for "Patients admitted to hospital, by age" and "Admission rates by age" don't supply any data, just metadata.

**Comment by xenatisch** [comment]
Hey @theosanderson, thanks for getting in touch.

Sorry about that. Thanks for reporting it. The cards that use custom settings (e.g. the ones with radio buttons or age/sex breakdowns) are rely on our contents team to enter the download endpoint manually... it sometimes goes wrong. 

I'll take a look as soon I find a few minutes.

**Comment by CharlotteDowns** [comment]
@xenatisch @PHEgeorginaanderson I came across the same issue this evening, is there a resolution yet?

**Comment by bm-1961** [comment]
Yes i had the same issue as well!

**Comment by xenatisch** [comment]
It seems to be working fine [here](https://coronavirus.data.gov.uk/api/v1/data?filters=areaType=nation;areaName=England&latestBy=&structure=%7B%22areaType%22:%22areaType%22,%22areaName%22:%22areaName%22,%22areaCode%22:%22areaCode%22,%22date%22:%22date%22,%22cumAdmissionsByAge%22:%22cumAdmissionsByAge%22%7D&format=json).

Might have been the firewall or high traffic? 

Anyhow, this isn't the API repo... issues concerning the API [v1](https://github.com/publichealthengland/coronavirus-dashboard-api-v1) and [v2](https://github.com/publichealthengland/coronavirus-dashboard-api-v2) should really go their respective repos

**Comment by bm-1961** [comment]
Please try downloading here:

https://coronavirus.data.gov.uk/details/download


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
