### ISSUE TITLE
Dashboard doesn't display data if link has a fbclid attached

### ISSUE THREAD

**Issue by jazzy-crane** [publichealthengland/coronavirus-dashboard#248]
**Describe the bug**
When clicking on a link to the coronavirus dashboard from Facebook, Facebook attaches a fbclid GET parameter. This is causing the dashboard to show N/A for all data, and not showing any charts

**To Reproduce**
Either:
1. Click https://coronavirus.data.gov.uk/?fbclid=IwAR1MYG7b451W00kQX-3C_RMHirt1IUNelfFdWHpe_oRtGDVAPLhJqXsOy_0
2. Send  https://coronavirus.data.gov.uk/ to someone on Facebook messenger (or post a comment, status etc.) and click the link

**Expected behaviour**
Expect to see full data such as clicking on  https://coronavirus.data.gov.uk/

**Screenshots**
Working:
![working](https://user-images.githubusercontent.com/33657082/95513651-96935a00-09b2-11eb-9836-d77e2a0bf1f4.png)

Not working:
![not working](https://user-images.githubusercontent.com/33657082/95513677-9f842b80-09b2-11eb-8433-d64c14bd109c.png)

N.B. the different URLs

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 85.0.4183.121 (Official Build) (64-bit) (cohort: Stable)

**Comment by xenatisch** [comment]
Thanks for getting in touch. 

I did see quite a few records in our logs with `fbclid` parameter. This is kind of an intentional behaviour. The issue in not so much `fbclid` as it is the length of its value, which exceeds the max that's allowed in our API. 

I'll see what I can do to exclude `fbclid`.

**Comment by joemclo** [comment]
Is there a list of known params that can be filtered on @xenatisch, so these can be excluded?

It doesn't seem to be the length of it's value now as even
`/cases?fbclid=aSDSAD` or `/cases?a=b` sees the same behaviour.

The api error is 
```
{"response":"Invalid Query: the query is either empty or does not conform to the correct pattern. See the API documentations for additional information.","status_code":412,"status":"Precondition Failed"}
```

**Comment by joemclo** [comment]
My reading of the docs make me think 
```
    const  structure = {
        areaType: "areaType",
        areaName: "areaName",
        areaCode: "areaCode",
        date: "date"
    };
``` from `src/common/utils/utils.js` are the valid params.

Happy to fix this if that's what is needed
