### ISSUE TITLE
https://coronavirus.data.gov.uk/downloads/csv/coronavirus-cases_latest.csv not working as of this morning.

### ISSUE THREAD

**Issue by cjw296** [publichealthengland/coronavirus-dashboard#250]
**Describe the bug**

https://coronavirus.data.gov.uk/downloads/csv/coronavirus-cases_latest.csv is serving up JS source rather than the csv that should be there. Docs say that while it is legacy, it's supported "for the foreseeable future".

**To Reproduce**
Steps to reproduce the behaviour:
1. `curl https://coronavirus.data.gov.uk/downloads/csv/coronavirus-cases_latest.csv`

**Expected behaviour**

The CSV that was there before.

**Additional context**

The code I'd using to download is here:

```
# download cases data
force_download = False
for_date = date.today()-timedelta(days=0)
suffix = 'csv'
for type_ in 'cases', 'deaths':
    path = base_path / f'coronavirus-cases_{for_date}.{suffix}'
    if force_download or not path.exists():
        download(cases_url.format(data_type=suffix), path)
```

**Comment by joannaburnett** [comment]
Having **exactly** the same problem here. Have tried mailing coronavirus-tracker@phe.gov.uk asking them to restore the file.

**Comment by joannaburnett** [comment]
OH! It's back! :-)
