### ISSUE TITLE
Log scale on graphs

### ISSUE THREAD

**Issue by mjmaisey** [publichealthengland/coronavirus-dashboard#294]
**Is your feature request related to a problem? Please describe.**
In the current period of rapid exponential case growth, it is difficult to interpret growth trends.

**Describe the solution you'd like**
A toggle to enable a log scale on relevant graphs (currently cases).

**Describe alternatives you've considered**
Using the export functionality and an external tool - significantly less convenient.

**Additional context**
N/A

**Comment by xenatisch** [comment]
Based on user research, it appears as though most users would find log scales too confusing. That is why have decided not to implement them.

You are welcome to contact us via the email provided on the dashboard to express you view, which we shall document for future considerations.
