### ISSUE TITLE
Map overlaps potentially misleading

### ISSUE THREAD

**Issue by HarryTrimble** [PublicHealthEngland/coronavirus-dashboard#30]
Big improvement on the page. Great work. And thank you for making the page's code available on GitHub. 

**Possible issue**; If you tab from countries to regions to councils, the overlapping colours could imply there are more case from one to the next, which isn't true. 

![Apr-16-2020 19-50-28](https://user-images.githubusercontent.com/12497586/79494843-94f86300-801b-11ea-8bc1-141c6c1c4a4f.gif)

Maps are hard, but just thought I would say. 

Keep up the great work!

**Comment by Ha-san-ali** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make Blobs on map more intuitive](https://trello.com/c/baFCi5o5/274-make-blobs-on-map-more-intuitive)

**Comment by Ha-san-ali** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Base circle radius scales at 0 cases and 0 pixels](https://trello.com/c/0ZzV54st/303-base-circle-radius-scales-at-0-cases-and-0-pixels)
