### ISSUE TITLE
map.png should not be served gzipped

### ISSUE THREAD

**Issue by acme** [publichealthengland/coronavirus-dashboard#300]
At the moment https://coronavirus.data.gov.uk/public/assets/frontpage/images/map.png is served from the homepage compressed with gzip:

```
❯ curl -sI --compressed https://coronavirus.data.gov.uk/public/assets/frontpage/images/map.png | egrep 'content-encoding|content-type'
content-type: image/png
content-encoding: gzip
```

Compressing already-compressed image formats such as PNG is a waste of time and CPU. The browser then has to decompress it unnecessarily which slows down the page load time a little.

I'm not sure which part of the stack is serving it, but map.png should not be served gzipped.

**Comment by xenatisch** [comment]
It's zipped by the CDN. I don't particularly see a reason to create a custom rule for it to be honest. 

I'm closing this as it's not a issue that's related to this repository.
