### ISSUE TITLE
Update time format

### ISSUE THREAD

**Issue by terrysimpson99** [publichealthengland/coronavirus-dashboard#304]
> Please ensure that the issue is related to the development of the service. Data and content issues do not fall into the remit of the development team unless they are not working as expected. Queries related to data and content should be directed to the email provided on the website.

**Describe the bug**
There is a leading zero in the time format at https://coronavirus.data.gov.uk/ It says 'Last updated on Monday 18 January 2021 at 04:43pm'.
This is also inconsistent with other pages such as https://coronavirus.data.gov.uk/details/testing which says: 'Last updated on Monday 18 January 2021 at 4:43pm'
GDS guidance is not to have leading zeros. See: https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#times

**To Reproduce**
Go to https://coronavirus.data.gov.uk/
Look at the top of the page where it says 'Last updated on '

**Expected behaviour**
The time format should not have a leading zero.

**Screenshots**
![image](https://user-images.githubusercontent.com/48089049/104953184-d14b5c00-59bd-11eb-8aff-e2506c648e63.png)

![image](https://user-images.githubusercontent.com/48089049/104953224-e2946880-59bd-11eb-8396-ad841216e82c.png)

**Desktop (please complete the following information):**
Windows 10
Chrome Version 87.0.4280.141 (Official Build) (64-bit)

**Comment by xenatisch** [comment]
No related to this repository - please report [here](https://github.com/publichealthengland/coronavirus-dashboard-frontend-server).
