### ISSUE TITLE
Update server-originated error message on postcode field

### ISSUE THREAD

**Issue by terrysimpson99** [publichealthengland/coronavirus-dashboard#305]
**Describe the bug**
This relates to the 'Enter a postcode' field at https://coronavirus.data.gov.uk/
While working on the bug report for the client-side error message at https://github.com/publichealthengland/coronavirus-dashboard/issues/303, I discovered a server-side error message which says '- please enter a full and valid UK postcode.'. GDS guidance is to style a message like 'Enter a ...' thus there is no hyphen no 'please'.

GDS guidance about error messages says "Do not use: ... ‘please’ because it implies a choice". See: https://design-system.service.gov.uk/components/error-message/

I also recommend checking:
1. if there is an error summary at the top of the page. This may help screenreader users
2. if the server-side error message works with screenreaders
I was unable to check either of these.

**To Reproduce**
Turn off client-side validation
Enter an invalid postcode 
System responds with '- please enter a full and valid UK postcode.'

**Expected behaviour**
I expect a system response to be something like 'Enter a UK postcode.'

**Screenshots**
https://github.com/publichealthengland/coronavirus-dashboard/issues/303
![image](https://user-images.githubusercontent.com/48089049/104956439-05c21680-59c4-11eb-97e1-ce25840ec59a.png)

**Desktop (please complete the following information):**
Laptop
Windows 10
Chrome Version 87.0.4280.141 (Official Build) (64-bit)

**Comment by xenatisch** [comment]
No related to this repository. Please report [here](https://github.com/publichealthengland/coronavirus-dashboard-frontend-server).

**Comment by rhubner** [comment]
@xenatisch : I may be wrong, but I can see pattern in this file : https://github.com/publichealthengland/coronavirus-dashboard/blob/v3-development/src/components/Map/Map.js#L631
