### ISSUE TITLE
Repeated labels on y-axes of cumulative charts on mobile

### ISSUE THREAD

**Issue by statsgeekclare** [publichealthengland/coronavirus-dashboard#328]
The y axis label is repeated when a user selects the cumulative chart for deaths within 28-days by date of death or by date of report on mobile devices.

The top two values both show 100k. 

The y axis labels are incorrect on cumulative first dose vaccinations - 20 million and 30 million are both repeated. 15 million shows as 20 million and 25 million shows as 30 million.

Steps to reproduce the behaviour:
1. Go to deaths details page on mobile
2. Click on cumulative on the first chart
3. See error.

The same steps produce an error on the first dose vaccinations chart.

**Expected behaviour**
No repetition of y-axis labels.

**Screenshots**
![deathscumulativecharterror](https://user-images.githubusercontent.com/70510599/114210951-fa91dd80-9957-11eb-8e25-b87c4394abdd.png)

**Smartphone (please complete the following information):**
 - Device: iPhone7
 - OS: iOS14.4.2
 - Browser: safari
 - Version: standard provided with iOS 14.4.2

**Additional context**
Could be a rounding error?

**Comment by statsgeekclare** [comment]
This also occurs on the vaccination uptake chart for second dose.
![20210408_173729](https://user-images.githubusercontent.com/70510599/114211445-8efc4000-9958-11eb-8a72-82366c02da4a.jpg)

**Comment by DaveJephson** [comment]
![Screenshot_20210509-123844_Chrome](https://user-images.githubusercontent.com/73355546/117577525-094beb80-b0e2-11eb-8248-f70780233436.jpg)

This one is incorrectly showing as 20M for values around 15M

**Comment by DaveJephson** [comment]
![chart](https://user-images.githubusercontent.com/73355546/117577703-c4748480-b0e2-11eb-9505-2f5097b9dc12.jpg)

This example shows 20M where it should be 15M
