### ISSUE TITLE
Change to rates description in cards on map page

### ISSUE THREAD

**Issue by DaveJephson** [publichealthengland/coronavirus-dashboard#329]
Change ‘Rolling rate’ to ‘Rate per 100,000 people’

**Comment by FloraDeath** [comment]
@xenatisch @DaveJephson Just wanted to check the progress of this one. You changed the rate text on the homepage and postcode search page but it still says rolling rate on the map page card. Is this in progress or dependent on something else? One of the main purposes of these changes was to make the rates text consistent acfross the site so it would be good to get this done soon. Thanks for your help.
