### ISSUE TITLE
Update developer guide to remove reference to nested queries

### ISSUE THREAD

**Issue by statsgeekclare** [publichealthengland/coronavirus-dashboard#331]
The developer guide page still contains examples of nested queries, for example under the "Renaming metrics" section. These need to be removed to reflect that nested queries are no longer possible.

**Comment by xenatisch** [comment]
Can't find them I'm afraid. Could you share a screenshot please?

**Comment by statsgeekclare** [comment]
You fixed this - it now makes it clear that nested queries are not possible. https://coronavirus.data.gov.uk/details/developers-guide#structure-renaming_metrics
