### ISSUE TITLE
Dates appear twice on hover-over on bar charts

### ISSUE THREAD

**Issue by statsgeekclare** [publichealthengland/coronavirus-dashboard#332]
**Describe the bug**
On the vaccinations given chart, the hover-over on daily doses is missing 17th April but instead show 16th April twice. The underlying data is correct.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Vaccinations detail page
2. Scroll down to Vaccinations given chart
3. Hover-over 17 April
4. See 16 April information twice

**Expected behaviour**
Expected to see information for 17 April.

**Screenshots**
![vaccsgivenerror](https://user-images.githubusercontent.com/70510599/115548511-761c5480-a29f-11eb-993e-479eb8b30451.png)

**Desktop (please complete the following information):**
 - OS: not supplied
 - Browser: not supplied
 - Version: not supplied

**Additional context**
This problem occurs for other charts - will add these to the issue as and when they occur.

**Comment by xenatisch** [comment]
This is related to the external library. It has a span thing against the last point that contains all of the figures. It applies to charts.

**Comment by xenatisch** [comment]
I have now opened [an issue](https://github.com/plotly/plotly.js/issues/5643) for this in the repository of the library that we use.
