### ISSUE TITLE
The API has stopped including a valid hash in returned queries. It worked until about 9 days ago but now returns null

### ISSUE THREAD

**Issue by renduh** [publichealthengland/coronavirus-dashboard#335]
API calls that request a hash such as this:
https://api.coronavirus.data.gov.uk/v1/data?filters=areaType=overview&structure={"date":"date","hash":"hash","newCases":"newCasesByPublishDate"}

Are returned with a null hash. 

It was working until April 19th. I have code that makes graphics from the feed and that stopped working then, so up until then the hash was being returned.

**Comment by xenatisch** [comment]
This is not related to this repository and should be raised for [APIv1](https://github.com/publichealthengland/coronavirus-dashboard-api-v1) instead.

The general answer would be that we have implemented some changes, and as such, the definition of hash has changed. This means that hash values now identify individual records and are no longer generated against the [areaType - areaCode - date] combination. For that reason and to prevent confusion, we have made the metric private as it was being used by very few users.
