### ISSUE TITLE
Overlapping text in Twitter card image

### ISSUE THREAD

**Issue by gwire** [publichealthengland/coronavirus-dashboard#337]
The text in the Twitter card image currently overlaps in several places, and is cropped.

[Example](https://coronavirus.data.gov.uk/downloads/og-images/og-summary_20210506.png)
![og-summary_20210506](https://user-images.githubusercontent.com/1095046/117345463-7a02c600-ae9e-11eb-95e2-a5a67016dacf.png)

**Comment by xenatisch** [comment]
Fixed in the ETL.
