### ISSUE TITLE
Improve display of graph image downloads on desktop

### ISSUE THREAD

**Issue by FloraDeath** [publichealthengland/coronavirus-dashboard#339]
**Is your feature request related to a problem? Please describe.**
Legends on graph image downloads ('dowload plot as png') appear very small in the default view, because of the high resolution. This makes them less usable and is only of benefit to people wanting to use the images for publication. This is particularly a problem with the vaccinations waffle on the vaccinations topic page, which has no axis labels, so is meaningless without clear legends.
<img width="368" alt="Waffle download desktop" src="https://user-images.githubusercontent.com/56301720/117478528-315b1380-af57-11eb-8d68-90d8408454ca.png">

**Describe the solution you'd like**
Design and engineering discussed this at a meeting. Pouria said he would investigate ways to improve how this display, such as defaulting to a lower resolution or improving how headings and legends display.

The meaning of the graph should be clear in the downloaded image. This would usually mean including:

- the heading
- legends in a readable size as default
- axis labels, where relevant

**Comment by AllyMD3** [comment]
Move to JIRA for action. Close
