### ISSUE TITLE
An LTLA API V2 download fails to return a file

### ISSUE THREAD

**Issue by theosanderson** [publichealthengland/coronavirus-dashboard#349]
Go to the Download page and download new cases by specimen date for LTLA Bolton, generating URL:

https://api.coronavirus.data.gov.uk/v2/data?areaType=ltla&areaCode=E08000001&metric=newCasesBySpecimenDate&format=csv

This returns an empty file.

**Comment by theosanderson** [comment]
(I have not verified how this relates to different metrics and LTLAs)

**Comment by xenatisch** [comment]
Thank you. This issue needs to go to the [APIv2.1 repository](https://github.com/publichealthengland/coronavirus-dashboard-api-v2-server). 

There is a [list of our current repositories](https://github.com/publichealthengland/coronavirus-dashboard#other-repositories), which you can use for future reference.
