### ISSUE TITLE
Incorrect display of daily vaccinations at local authority level 

### ISSUE THREAD

**Issue by fruzsinaagocs** [PublicHealthEngland/coronavirus-dashboard#359]
**Describe the bug**
At the local authority level (after typing in a postcode), the number of daily vaccinations for both the first and second doses is incorrect. Under **Daily**, the total number is displayed up to _and including_ the current date, and under **Total**, up to _but not including_ the current date. This results in the total vaccinations appearing to be lower than the daily ones.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://coronavirus.data.gov.uk/
2. Under "What's the situation in your current area?", enter a postcode, e.g. OX1 4AU, and hit search
3. Scroll down to "Additional relevant data available for OX1 4AU:", and look under the "Vaccinations" tab, "Daily" and "Total" for the 1st and 2nd dose

**Expected behaviour**
The daily vaccination numbers should be lower than the total, and should match those found when following the "All vaccination data" link on the local authority level page. 

**Screenshots**
![covid_dashboard_bug](https://user-images.githubusercontent.com/19972401/120829532-6c039c00-c555-11eb-97b8-4c6706a599fe.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Version: 89.0

**Comment by xenatisch** [comment]
Thank you for reporting this.

It was a data related issue which has now been fixed. Can't flush the cache until the traffic subsides, I'm afraid.

For future reference, landing + postcode page issues go to the [Homepage Server repository](https://github.com/publichealthengland/coronavirus-dashboard-frontend-server).

**Comment by fruzsinaagocs** [comment]
Thanks, got it!
