### ISSUE TITLE
PHE logo / attribution on charts

### ISSUE THREAD

**Issue by drduncanrobertson** [PublicHealthEngland/coronavirus-dashboard#369]
> Please ensure that the issue is related to the development of the service. Data and content issues - including visualisations and hierarchy - do not fall into the remit of the development team.  Queries related to data and content should be directed to the email provided on the website.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Credit on charts similar to how Our World In Data display their graph - logo in top right, source credit in bottom left.

**Describe alternatives you've considered**

**Additional context**
People screenshot the dashboard charts meaning that there is no attribution on the chart when they do so.  Adding source credits to coronavirus.data.gov.uk would be beneficial.

![Screenshot 2021-06-08 102000](https://user-images.githubusercontent.com/64782597/121159453-1c69ec80-c843-11eb-9440-3b8c503f0dcf.png)

**Comment by xenatisch** [comment]
Thank you for the recommendation. I will certainly run it by our team.

**Comment by DaveJephson** [comment]
Suggest including an option to save as an image would reduce screenshots being taken. If this were to be implemented, we could add a source line bottom left, similar to the example shown. If we were to also include the logo, it should meet the usage requirements around size/location for government branding.

**Comment by AllyMD3** [comment]
Moved to JIRA for action. Close
