### ISSUE TITLE
MSOA counts less-than-3 inferrable on weekly delta [minor privacy issue]

### ISSUE THREAD

**Issue by penguin42** [PublicHealthEngland/coronavirus-dashboard#376]
> Please ensure that the issue is related to the development of the service. Data and content issues do not fall into the remit of the development team unless they are not working as expected. Queries related to data and content should be directed to the email provided on the website.

**Describe the bug**
On the map view, when an MSOA has more than 3 cases, a delta is shown against the previous weeks number of cases;
where the previous week had less than 3 cases (which were hidden by the privacy mechanism) the delta in the current weeks data allows you to calculate the data that was previously hidden.
(I can't find the code that produces the delta in the API code; is it actually in that or lower down?)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://coronavirus.data.gov.uk/details/interactive-map
2. Zoom into MSOA level, and find an MSOA with not many more than 3 cases that had less than 3 last week
3. See the delta allowing you to see last weeks actual data

**Expected behaviour**
The delta shouldn't be provided by the API in the case where either the current or previous weeks cases is below the threshold.

**Comment by xenatisch** [comment]
Thank you for getting in touch. 

This is technically a data-related issue, but I am happy to provide some insight. 

You indicated:

> [...] an MSOA with not many more than 3 cases that had less than 3 last week.

and 

> [...] when an MSOA has more than 3 cases, a delta is shown against the previous weeks number of cases; where the previous week had less than 3 cases (which were hidden by the privacy mechanism) the delta in the current weeks data allows you to calculate the data that was previously hidden.

I think the issue you have raised stems from a common misconception regarding MSOA data. We have never published *the number of cases* at MSOA level - only the *seven-day rolling sum*. The rolling sum is also the metric based on which we run the suppression algorithm, and calculate the change and percentage change metrics. To that end, in order to calculate the suppressed figures on a specific day, you will need to work out the exact date on which a specific case was declared.

For that reason, I don't believe that there is a risk of disclosure. However, if you are still concerned, I am happy to refer this to the head of profession for statistics and / or the head of indicators for a review.

Hope this helps.

**Comment by penguin42** [comment]
> Thank you for getting in touch.

Thanks for the quick reply

> This is technically a data-related issue, but I am happy to provide some insight.
> 
> You indicated:
> 
> > [...] an MSOA with not many more than 3 cases that had less than 3 last week.
> 
> and
> 
> > [...] when an MSOA has more than 3 cases, a delta is shown against the previous weeks number of cases; where the previous week had less than 3 cases (which were hidden by the privacy mechanism) the delta in the current weeks data allows you to calculate the data that was previously hidden.
> 
> I think the issue you have raised stems from a common misconception regarding MSOA data. We have never published _the number of cases_ at MSOA level - only the _seven-day rolling sum_. The rolling sum is also the metric based on which we run the suppression algorithm, and calculate the change and percentage change metrics. To that end, in order to calculate the suppressed figures on a specific day, you will need to work out the exact date on which a specific case was declared.

Thanks; and I checked your API will only give the rolling sum once per week (e.g. 24th May, then 31st, not inbetween).
 However, I don't think it really changes the question.

> For that reason, I don't believe that there is a risk of disclosure. However, if you are still concerned, I am happy to refer this to the head of profession for statistics and / or the head of indicators for a review.

What I still don't understand is that; is if the suppression algorithm is based on the rolling sum for a given date; and then I look at the rolling sum for the next week, subtracting the delta gives me the rolling sum for the first date doesn't it?  If it does, that's exactly the data that was suppressed isn't it?

> 
> Hope this helps.

Thanks

**Comment by xenatisch** [comment]
It does, but that's only the rolling sum. One could argue that the sum could occasionally yield 1, but that's a compromise of sorts. The change is quite important to most people, and most MSOAs tend to fluctuate around 3 to 6, so removing the delta would have quite a substantial impact in the consistency of presentation. 

MSOAs cover a population of ~8k+, so it's still not easy to identify a person specially given the number of tests that are being conducted + it won't be easy to work out the numbers unless you're an analyst. 

I recommend you send us an email on coronavirus-tracker@phe.gov.uk . Your query will then be forwarded to our data team who will be able to provide a more in-depth answer.  We usually don't deal with issues such as this on GitHub and they are not related to the technical and development team.

**Comment by penguin42** [comment]
OK, thanks - will do!
