### ISSUE TITLE
Changes to cases map

### ISSUE THREAD

**Issue by FloraDeath** [PublicHealthEngland/coronavirus-dashboard#385]
This is the revised text for the cases map, agreed with Clare and Dave.

**1. Text to go above the map:**

### Interactive map
This map shows 7-day case rate per 100,000 people.
The default view shows data by local authority. Zoom in for more local data.

Case rate per 100,000 people for 7-day period ending on 04 Jun 2021: 

**2. Text to go below the map:**

### Case rates

Case rates are shown per 100,000 people for the 7-day period ending on the date shown. We calculate this by dividing the 7-day total by the area population and multiplying by 100,000.

This makes it easier to compare cases across areas of different population size.

### Map areas
Find your area by using the postcode search or the zoom.
The map shows data for different area types:

- local authorities. These are divided into Upper Tier Local Authorities (UTLA) and Lower Tier Local Authorities (LTLA) for areas with 2 tiers of local government, such as county council (upper tier) and district council (lower tier).
- Middle layer Super Output Areas (MSOA). These areas are smaller than local authorities, so show data at the most local level.

### Data not shown

There are 2 reasons why data may not be shown:

- for areas with fewer than 3 cases at MSOA level, we do not show data to protect individuals' identities. 
- data may be missing, for example because it is delayed or unavailable. If you zoom in to MSOA level, data for Northern Ireland, Scotland and Wales are not available.

### Copyright information

All data used in the map are available in the public domain and may be downloaded from the relevant section of the website or via the API.

- Contains MSOA names © Open Parliament copyright and database right 2020
- Contains Ordnance Survey data © Crown copyright and database right 2020
- Contains Royal Mail data © Royal Mail copyright and database right 2020
- Contains Public Health England data © Crown copyright and database right 2020
- Office for National Statistics licensed under the Open Government Licence v.3.0

Lookup products and data are supplied under the Open Government Licence. You must use the above copyright statements when you reproduce or use the materials, data, digital boundaries or postcode products used in this page.

**3. Key:**

Change title to 'Case rate' and first label to 'Data not shown'
![New key labels](https://user-images.githubusercontent.com/56301720/122245912-08b32b80-cebe-11eb-88f0-d70136181554.png)

**4. Card text**

- Change 'Rolling rate' to 'Case rate per 100,000 people'

- Add UTLA/LTLA/MSOA label under name

- Remove diamond comparison bar
<img width="352" alt="Revised map card design" src="https://user-images.githubusercontent.com/56301720/122248978-621c5a00-cec0-11eb-9663-852dd8bb10e2.png">

**4. Card text for under 3 cases**

Change to:
Under 3 cases. For smaller areas (MSOAs) with fewer than 3 cases, we do not show data. This is to protect individuals' identities.
<img width="169" alt="Revised map card design under 3 cases" src="https://user-images.githubusercontent.com/56301720/122249281-9c85f700-cec0-11eb-808e-b0fe3f3aa90a.png">

Design for complete revised page:
![Cases map design](https://user-images.githubusercontent.com/56301720/122251380-5b8ee200-cec2-11eb-8657-d79cad17bdc7.png)

**Comment by xenatisch** [comment]
Hi @FloraDeath 

Just a quick note: the addition of vaccinations map is not related to this issue, so it won't be addressed as a part of the fix.
