### ISSUE TITLE
Copyright attributions on the map

### ISSUE THREAD

**Issue by xenatisch** [PublicHealthEngland/coronavirus-dashboard#400]
To avoid the 'i' overlapping with the rest of the boxes, if possible, move it just outside the box.

![Mobile Changes](https://user-images.githubusercontent.com/12953178/123302245-683fb580-d514-11eb-84ee-965fa5f807c9.png)

**Comment by beawitcht** [comment]
To maintain copyright requirements the attribution must stay within the map. The next commit for this issue will move the legend above the copyright notice to fix the clipping issue
