### ISSUE TITLE
manifest.json is missing on website

### ISSUE THREAD

**Issue by acme** [PublicHealthEngland/coronavirus-dashboard#43]
The HTML pages link to a Web app manifest `manifest.json`: https://github.com/PublicHealthEngland/coronavirus-dashboard/blob/development/public/index.html#L13 but this manifest does not seem to be present on the website as https://coronavirus.data.gov.uk/manifest.json gives a 404 Not Found error response.

**Comment by Ha-san-ali** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [manifest.json is missing on website](https://trello.com/c/26CtJR7g/278-manifestjson-is-missing-on-website)

**Comment by xenatisch** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Does not work with javascript turned off. We need a fallback option.](https://trello.com/c/mS3s4WiE/134-does-not-work-with-javascript-turned-off-we-need-a-fallback-option)

**Comment by Ha-san-ali** [comment]
@acme This has now been addressed thanks to @xenatisch. Issue can be closed

**Comment by acme** [comment]
Thanks! This looks good.
