### ISSUE TITLE
7-day averages not displaying correctly

### ISSUE THREAD

**Issue by ckelly17** [PublicHealthEngland/coronavirus-dashboard#436]
On the cases by date reported chart, the 7-day average line cuts off the last three days and appears to have the 7-day avg values shifted back three days as well. For example the 7-day average for 21 July is 47,695.7, but this is instead the value shown for 18 July. The actual 7-day avg on 18 July is 45,241. Is this because the 7-day average takes the current day, as well as the three days before and the three days after, instead of using the average over the current day and the prior six?

**Comment by xenatisch** [comment]
Hi. This is a data issue and needs to be directed to the data team thorough the email.

Generally speaking, such matters are explained extensively in the "About the data" page too.

To answer your questions:
- The rolling average is centre aligned, not right aligned. 
- The data in event date metrics (specimen date) are incomplete for the most recent 5 days. The average is therefore not calculated and the values are displayed in grey.

**Comment by ckelly17** [comment]
Thank you!
