### ISSUE TITLE
Death accumulated number issues

### ISSUE THREAD

**Issue by efaysal** [PublicHealthEngland/coronavirus-dashboard#439]
Hello,

The accumulated number has to be increasing all the time.
So why is it not for some regions in your public data, as Brent, Croydon, Enfield and so on?

Thanks for fixing these issues.

**Comment by xenatisch** [comment]
This is not a development related issue. Data issues should be queried using the email provided on the website.

Re your question; there have been changes to the calculation methodology, and reporting date records are regarded as immutable - i.e. they are not reviewed after publication. 

See the "About" tab on each card or visit the "About the data" page to read more on such changes and impact thereof.
