### ISSUE TITLE
utlas.geojson is requested twice

### ISSUE THREAD

**Issue by dracos** [PublicHealthEngland/coronavirus-dashboard#44]
On pageload, both Map.js and utlaLayer.js load utlas.geojson, so it's requested twice from the server (should be cached after first fetch hopefully, unless they both request at the same time I guess, which they might well do on first load I imagine). I wasn't sure of the best way of changing this, and I realise you may be changing this anyway, hence opening an issue rather than a PR. Hope that's helpful.

**Comment by xenatisch** [comment]
Good point. It certainly is cached, it's async, so should deteriorate the service. But it should nonetheless be removed. Thanks @dracos, we appreciate your contributions.

**Comment by xenatisch** [comment]
@neb42 any thoughts on this?

**Comment by Ha-san-ali** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [utlas.geojson is requested twice](https://trello.com/c/W7gtfDZj/323-utlasgeojson-is-requested-twice)

**Comment by xenatisch** [comment]
This was fixed in [release v1.6.0](https://github.com/PublicHealthEngland/coronavirus-dashboard/releases/tag/1.6.0).
