### ISSUE TITLE
Death Cumulative Sum Issues

### ISSUE THREAD

**Issue by efaysal** [PublicHealthEngland/coronavirus-dashboard#440]
Cumulative Sum  has to be increasing all the time regardless of the method used to count the number of daily death. 
So why is it not for some regions in your public data, as Brent, Croydon, Enfield and so on?

This is a serious issue related to development of your calculation and please try to provide a convincing answer instead of to be expeditive and elusive. 

cum-sum  works on successive daily reported deaths and returns the cumulative sums and should be always increasing otherwise you are just reporting garbage and junk data.

**Comment by xenatisch** [comment]
This has been answered in #439.

**Comment by efaysal** [comment]
your answer is not acceptable. Cumulative Sum has to be increasing all the time regardless of the method used to count the number of daily death.

**Comment by efaysal** [comment]
Stop adding stereotype on this issue,  xenatisch added duplicate invalid NonDev and removed bug labels 1 minute ago, 

answer the question why the Cumulative Sum is NOT  increasing all the time?

**Comment by xenatisch** [comment]
I'm sorry, but it is not for the development team to respond to queries that are not related to the development team! Please read the [documentation on deaths](https://coronavirus.data.gov.uk/details/about-data#daily-and-cumulative-deaths-within-28-days-of-a-positive-test) in the "About the data" page or get in touch via the email provided on the website.

**Comment by xenatisch** [comment]
From the documentation:

> On 16 June 2021 the way deaths are allocated to local authorities and regions in England changed to take account of the address at death registration first. Because of this, the cumulative number of deaths in each affected local authority and region changed. This improvement means that there will be fewer changes to the geographical allocation of historical death counts in future.
>
> Due to a processing update, 141 historical deaths within 28 days in England were excluded from the published data on 21 November 2020. This issue was corrected for data published on 22 November 2020, which included deaths omitted on 21 November 2020 within the total and daily number of newly reported deaths for 22 November 2020.

**Comment by efaysal** [comment]
cumulative number of deaths SHOULD BE ALWAYS INCREASING , ITS MATHEMATICS. 
IF NOT INCREASING THEN YOU DO HAVE A SERIOUS ISSUE, TRY TO FIX IT.

**Comment by efaysal** [comment]
cum-sum works on successive daily reported deaths and returns the cumulative sums and should be always increasing otherwise you are just reporting garbage and junk data.

**Comment by xenatisch** [comment]
This is not related to the development team. It is **not** our job, or our decision to change calculation methodology. What you're saying here will not be taken into consideration. I cannot be any clearer. 

You are wrong, but if you feel so strongly, you are welcome to email us. This is the last time I am responding to your issue. Please stop spamming the repository and our contributors.

**Comment by efaysal** [comment]
Any way, you have be advised about the issue, if not fixed I will report it  to the people I m collaborating  with(it is a voluntary task).

This is not spamming the repository and our contributors, i m reporting a logical error, any one with basic understanding of cum-sum will be surprised ...

**Comment by xenatisch** [comment]
Report it to anyone you wish, but do not threaten public servants. 

You need to learn about the difference between mutable and immutable reporting of data + the difference between event and reporting date metrics. 

You are very much spamming us right now. I have told you several times that this is not an issue for our team to consider, but you keep going on about it. Stop.
