### ISSUE TITLE
Vaccinations waffle showing off to right on summary page

### ISSUE THREAD

**Issue by rachelupstairs** [PublicHealthEngland/coronavirus-dashboard#476]
The waffle chart for people vaccinated is falling off the right side of the grey rectangle. 
User reported this issue in Edge and Firefox, I am also seeing the same in Chrome. 
![image](https://user-images.githubusercontent.com/86053764/131819104-83ae8990-262e-4561-ba1c-b6245432127a.png)

**Comment by xenatisch** [comment]
Fixed in the relevant repository.
