### ISSUE TITLE
"Booser" typo on  "Vaccination uptake, by report date" chart

### ISSUE THREAD

**Issue by RobHannay** [PublicHealthEngland/coronavirus-dashboard#503]
> Please ensure that the issue is related to the development of the service. Data and content issues do not fall into the remit of the development team unless they are not working as expected. Queries related to data and content should be directed to the email provided on the website.

**Describe the bug**
Legend label for booster says "Booser" on "Vaccination uptake, by report date" chart.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://coronavirus.data.gov.uk/details/vaccinations
3. Scroll down to "Vaccination uptake, by report date"

**Expected behaviour**
For it to say "Booster"

**Screenshots**
![image](https://user-images.githubusercontent.com/609062/139037347-5d26ecac-69e8-4e5f-89dd-660bd8599d61.png)

**Desktop:**
 - OS: Mac OS 11
 - Browser Firefox Developer Edition
 - Version 94

**Comment by jamesbwestwood** [comment]
Thank you, great spot. This is now fixed.
