### ISSUE TITLE
Local pages design and copy improvements

### ISSUE THREAD

**Issue by martafioni** [PublicHealthEngland/coronavirus-dashboard#505]
There are currently some issues with text wrapping on mobile that can be solved by applying the suggested text and design changes: 

- substitute 'By date of specimen in the seven days to 26 October 2021' with ' Seven days to 26 October 2021' . this is going to make the text shorter so stays in one line, and also make it consistent with the labels we use in the map pages for the same data. 

- substitute 'last 7 days' with ' total cases', making it match the map pages. 

- Align the blocks with numbers singularly on the right, like in the attached design, to eliminate the layout problems. Do this consistently with the cases data, and with vaccination data. 

- text under 'other data for your area' can be a single block. Third sentence ( 'For example') can start in a new line. 

- size of text for bold numbers and titles can be increased. 

<img width="210" alt="Screenshot 2021-11-01 at 14 58 51" src="https://user-images.githubusercontent.com/12953178/139692492-914c62b2-fe34-464c-9cbf-23ed3a6c5ffe.png">

![Local Pages V2 - Mobile](https://user-images.githubusercontent.com/12953178/139692698-bdf3e070-bb60-4172-90dd-cd6b4a154746.png)

**Comment by AllyMD3** [comment]
Converted to JIRA ticket for progression. This issue can be closed.
