### ISSUE TITLE
No weekly data available for vaccinations

### ISSUE THREAD

**Issue by przemyslawpluta** [PublicHealthEngland/coronavirus-dashboard#510]
**Describe the bug**
It appears there are no weekly vaccination data available for England, and Scotland. Query with weeklyPeopleVaccinatedFirstDoseByVaccinationDate and weeklyPeopleVaccinatedSecondDoseByVaccinationDate return null while Wales and Northern Ireland data seems to stop in Feb.

**To Reproduce**

Query England: https://coronavirus.data.gov.uk/api/v1/data?filters=areaType=nation;areaName=England&structure={"areaType":"areaType","areaName":"areaName","areaCode":"areaCode","date":"date","weeklyPeopleVaccinatedFirstDoseByVaccinationDate":"weeklyPeopleVaccinatedFirstDoseByVaccinationDate","cumPeopleVaccinatedFirstDoseByVaccinationDate":"cumPeopleVaccinatedFirstDoseByVaccinationDate","weeklyPeopleVaccinatedSecondDoseByVaccinationDate":"weeklyPeopleVaccinatedSecondDoseByVaccinationDate","cumPeopleVaccinatedSecondDoseByVaccinationDate":"cumPeopleVaccinatedSecondDoseByVaccinationDate"}&format=json

Query Scotland: https://coronavirus.data.gov.uk/api/v1/data?filters=areaType=nation;areaName=Scotland&structure={"areaType":"areaType","areaName":"areaName","areaCode":"areaCode","date":"date","weeklyPeopleVaccinatedFirstDoseByVaccinationDate":"weeklyPeopleVaccinatedFirstDoseByVaccinationDate","cumPeopleVaccinatedFirstDoseByVaccinationDate":"cumPeopleVaccinatedFirstDoseByVaccinationDate","weeklyPeopleVaccinatedSecondDoseByVaccinationDate":"weeklyPeopleVaccinatedSecondDoseByVaccinationDate","cumPeopleVaccinatedSecondDoseByVaccinationDate":"cumPeopleVaccinatedSecondDoseByVaccinationDate"}&format=json 

Query Wales: https://coronavirus.data.gov.uk/api/v1/data?filters=areaType=nation;areaName=Wales&structure={"areaType":"areaType","areaName":"areaName","areaCode":"areaCode","date":"date","weeklyPeopleVaccinatedFirstDoseByVaccinationDate":"weeklyPeopleVaccinatedFirstDoseByVaccinationDate","cumPeopleVaccinatedFirstDoseByVaccinationDate":"cumPeopleVaccinatedFirstDoseByVaccinationDate","weeklyPeopleVaccinatedSecondDoseByVaccinationDate":"weeklyPeopleVaccinatedSecondDoseByVaccinationDate","cumPeopleVaccinatedSecondDoseByVaccinationDate":"cumPeopleVaccinatedSecondDoseByVaccinationDate"}&format=json

Query Northern Ireland: https://coronavirus.data.gov.uk/api/v1/data?filters=areaType=nation;areaName=Northern%20Ireland&structure={"areaType":"areaType","areaName":"areaName","areaCode":"areaCode","date":"date","weeklyPeopleVaccinatedFirstDoseByVaccinationDate":"weeklyPeopleVaccinatedFirstDoseByVaccinationDate","cumPeopleVaccinatedFirstDoseByVaccinationDate":"cumPeopleVaccinatedFirstDoseByVaccinationDate","weeklyPeopleVaccinatedSecondDoseByVaccinationDate":"weeklyPeopleVaccinatedSecondDoseByVaccinationDate","cumPeopleVaccinatedSecondDoseByVaccinationDate":"cumPeopleVaccinatedSecondDoseByVaccinationDate"}&format=json 

**Expected behaviour**
Get weekly numbers for vaccination per nation.

**Comment by xenatisch** [comment]
Weekly metrics were deprecated long ago. Use `newPeopleVaccination...` instead.

**Comment by przemyslawpluta** [comment]
@xenatisch thanks.
