### ISSUE TITLE
Naming inconsistencies 

### ISSUE THREAD

**Issue by przemyslawpluta** [PublicHealthEngland/coronavirus-dashboard#512]
**Describe the bug**
There is naming inconsistency between first, second and third doses. Required parameters are as per below and for some reason **Dose** has been superseded by **Injection** for Third dose?

- newPeopleVaccinatedFirst**Dose**ByPublishDate
- cumPeopleVaccinatedFirst**Dose**ByPublishDate
- newPeopleVaccinatedSecond**Dose**ByPublishDate
- cumPeopleVaccinatedSecond**Dose**ByPublishDate
- newPeopleVaccinatedThird**Injection**ByPublishDate
- cumPeopleVaccinatedThird**Injection**ByPublishDate

**To Reproduce**
Query: https://coronavirus.data.gov.uk/api/v1/data?filters=areaType=nation;areaName=England&structure={"areaType":"areaType","areaName":"areaName","areaCode":"areaCode","date":"date","newPeopleVaccinatedFirstDoseByPublishDate":"newPeopleVaccinatedFirstDoseByPublishDate","cumPeopleVaccinatedFirstDoseByPublishDate":"cumPeopleVaccinatedFirstDoseByPublishDate","newPeopleVaccinatedSecondDoseByPublishDate":"newPeopleVaccinatedSecondDoseByPublishDate","cumPeopleVaccinatedSecondDoseByPublishDate":"cumPeopleVaccinatedSecondDoseByPublishDate","newPeopleVaccinatedThirdInjectionByPublishDate":"newPeopleVaccinatedThirdInjectionByPublishDate","cumPeopleVaccinatedThirdInjectionByPublishDate":"cumPeopleVaccinatedThirdInjectionByPublishDate"}&format=json 

**Expected behaviour**
Fallow naming convention.

**Comment by xenatisch** [comment]
This isn't really an issue related to the development team. As outlined on the dashboard, the third one includes the booster dose and the third dose - and they are not the same thing; hence the name.
