### ISSUE TITLE
Query Question

### ISSUE THREAD

**Issue by przemyslawpluta** [PublicHealthEngland/coronavirus-dashboard#513]
**Question**
Using https://coronavirus.data.gov.uk/details/download and metric of **vaccinationsAgeDemographics** query https://api.coronavirus.data.gov.uk/v2/data?areaType=nation&areaName=England&metric=vaccinationsAgeDemographics&format=json can be used but is there a way to select only specific property e.g. **age** and **VaccineRegisterPopulationByVaccinationDate** instead of all currently returned?

**Comment by xenatisch** [comment]
No

**Comment by przemyslawpluta** [comment]
@xenatisch thanks
