### ISSUE TITLE
Inconsistent Behaviour in CSV download for daily deaths with covid 19 on the death certificate

### ISSUE THREAD

**Issue by tonyjward-dhsc** [PublicHealthEngland/coronavirus-dashboard#524]
**Describe the bug**
The csv download button for Daily deaths with COVID-19 on the death certificate by date of death is not consistent. In the last couple of weeks incomplete deaths are provided. However more than 2 weeks ago incomplete deaths were not provided. 

**To Reproduce**
Steps to reproduce the behaviour:
Download the data and compare it to the visualisation. 

**Expected behaviour**
I would expect that incomplete data be either consistently provided, or consistently not provided in the download. This is not the case

**Comment by xenatisch** [comment]
This is not really a development issue, but the methodologies for all metrics are outlined in their documentations.

I'm not sure I understand your query, but have a look at [the docs](https://coronavirus.data.gov.uk/metrics/doc/newOnsDeathsByRegistrationDate). Feel free to get back to us if the answer isn't clear. 

Please bear in mind that we are reliant on external sources for the data and can only publish that which we receive. It may be that the data were delayed. We do our best to provide consistent data, but that depends on the consistency of the data we receive.

**Comment by tonyjward-dhsc** [comment]
I have looked at the documentation. It seems like documentation exists for the deaths within 28 days of a covid test, but does not exists for daily deaths with covid 19 on the death certificate. 

From https://coronavirus.data.gov.uk/details/deaths it says "There is a lag in reporting of at least 11 days because the data are based on death registrations"

In this screen shot I compare two data extracts taken a week a part. The left most plot has incomplete data present - and we know this because a week later the number is higher.
![incomplete data](https://user-images.githubusercontent.com/81575331/144251004-c96d7a46-d6a6-4b3e-b421-1635a8874d0d.PNG)

So to clarify this bug relates to whether you supply the data that relate to the 11 day window (reporting lag). Mid September you were not providing it. and at some point in October you started providing it.

**Comment by statsgeekclare** [comment]
The documentation for the death certificate deaths is here https://coronavirus.data.gov.uk/metrics/doc/newDailyNsoDeathsByDeathDate

If you are still experiencing issues with the data please email coronavirus-tracker@phe.gov.uk
