### ISSUE TITLE
Cases definition to include multiple infection episodes from 31 January 2022

### ISSUE THREAD

**Issue by przemyslawpluta** [PublicHealthEngland/coronavirus-dashboard#554]
As per [From 31 January 2022, UKHSA will move all COVID-19 case reporting](https://coronavirus.data.gov.uk/details/whats-new/record/af008739-ffa3-47b8-8efc-ef109f2cfbdd) in England to use a new episode-based definition which includes possible reinfections.

On the dashboard, this means:
- cases in England by report date will change to the new definition of an episode of infection
- specimen date metrics will be revised back to the beginning of the pandemic
- ...

Does it mean that current naming convention for cases **newCasesByPublishDate**, **cumCasesByPublishDate**, **newCasesBySpecimenDate**, **cumCasesBySpecimenDate** etc. will change or only data will change from 31 January 2022 to match new methodology but naming convention will stay the same?

**Comment by jamesbwestwood** [comment]
The naming convention for these metrics will stay the same.
The definition is changing so:

- for the Publish date metrics the change will be for new data from 31 Jan (historical data will not change)
- for the Specimen date metrics the entire back series will change on 31 Jan

As ever, the archive will be available allowing the download of metrics as published on specific dates.
