### ISSUE TITLE
Error in screenreader text

### ISSUE THREAD

**Issue by FloraDeath** [PublicHealthEngland/coronavirus-dashboard#576]
There is a typo in the screen reader only text on the up arrow trends on charts. Remove space in the word "of". Currently announced as two letters: "o" "f"

Feedback from user:
The text assigned to up and down arrows that gets voiced by screen readers. is quite nice but... Down arrows work OK but up arrows have a typo in the text associated with them. Instead of the word "of" it says "o f" i.e. 2 letters with a space in-between.

**Comment by statsgeekclare** [comment]
This has now been corrected.
