### ISSUE TITLE
Overview Data for United Kingdom is Not Working

### ISSUE THREAD

**Issue by ian-jarrett** [PublicHealthEngland/coronavirus-dashboard#578]
Something seems to have changed in the API (from April/May 2022?). The following filters no longer work:
  areaType="overview";areaName="United+Kingdom";
but give the error:
{
    "response": "Query parameter 'areaNam' (areaNam  e) is invalid. Did you mean 'areaName'?",
    "status_code": 400,
    "status": "Bad request"
}
It I remove the quotes from filter and replace the "+" with a Space, with this filter:
  areaName=United%20Kingdom;areaType=overview
It returns 204, No Content.
Queries to other areaNames with other areaTypes work OK:
If I try a nation (England) instead of the UK with this filter:
  ?filters=areaName="England";areaType="nation"
It also returns error 400 ("Query parameter" is wrong)
But if I remove the quotes from the filter:
  ?filters=areaName=England;areaType=nation
Everything works as expected.

Something appears to have changed on the server side that is processing the filter in the URL? Can you investigate pls?

**Comment by ian-jarrett** [comment]
United Kingdom overview data is available up to May 20th 2022, then it breaks. From then onwards, only nation data (England, Wales, Scotland) seems to work.

**Comment by przemyslawpluta** [comment]
Can see the same ... UK is basically stack on May 20th 2022 and no updates since.

**Comment by statsgeekclare** [comment]
This is an issue with the data not the service - UK data for many metrics ceased on 20 May 2022 when Northern Ireland's data reporting stopped.
