### ISSUE TITLE
Blank values in cumulative counts csv

### ISSUE THREAD

**Issue by AndyELich** [PublicHealthEngland/coronavirus-dashboard#59]
Please can you fix the blank values in the cumulative counts csv. If there are no new cases the number should be the same as the previous day. The blank values have to be corrected before we can analyse the data

**Comment by xenatisch** [comment]
Related to the [pipeline ETL](https://github.com/PublicHealthEngland/coronavirus-dashboard-pipeline-etl). Under review.

**Comment by xenatisch** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Areas with 0 reported cases sometimes not included in dataset](https://trello.com/c/SGf0NfHF/279-areas-with-0-reported-cases-sometimes-not-included-in-dataset)
