### ISSUE TITLE
Invalid HTTPS certificate

### ISSUE THREAD

**Issue by nARN** [PublicHealthEngland/coronavirus-dashboard#603]
> Please ensure that the issue is related to the development of the service. Data and content issues do not fall into the remit of the development team unless they are not working as expected. Queries related to data and content should be directed to the email provided on the website.

**Describe the bug**
https://coronavirus.data.gov.uk presents a generic Azure's certificate, which is not valid for this domain. The issue is made worse by HSTS. Even though HSTS does not appear to be enabled at the moment several devices that I own remember it from earlier and refuse to even add an exception.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://coronavirus.data.gov.uk
2. See error

**Expected behaviour**
A valid certificate is expected

**Screenshots**
![Screenshot from 2022-10-17 13-50-41](https://user-images.githubusercontent.com/4236273/196181496-5e191694-4f08-46cb-8f70-a8751b7daf6f.png)

**Desktop (please complete the following information):**
 - OS: windows/linux/android
 - Browser: chrome/firefox
 - Version: multiple

**Comment by nARN** [comment]
Correction: I claimed that api.coronavirus.data.gov.uk was affected. This is incorrect and the certificate there is valid. I was confused by the redirect from there to coronavirus.data.gov.uk. I corrected the description of the bug now.

**Comment by statsgeekclare** [comment]
This is now fixed.
