### ISSUE TITLE
Outdated Total number of lab-confirmed UK cases in the dashboard

### ISSUE THREAD

**Issue by przemyslawpluta** [PublicHealthEngland/coronavirus-dashboard#71]
**Total number of lab-confirmed UK cases** in the [coronavirus.data.gov.uk](https://coronavirus.data.gov.uk/) dashboard is outdated as of **Last updated 27 Apr 2020, 7:48pm** and indicates **152,840** same as yesterday while it should be **157,149** as per [coronavirus-covid-19-information-for-the-public](https://www.gov.uk/guidance/coronavirus-covid-19-information-for-the-public).

<img width="1175" alt="dash" src="https://user-images.githubusercontent.com/221250/80411754-9e5bb800-88c4-11ea-8b24-8d0b18b1912a.png">

<img width="668" alt="site" src="https://user-images.githubusercontent.com/221250/80411774-a3206c00-88c4-11ea-8078-c1535a34c02e.png">

**Comment by xenatisch** [comment]
Hi @przemyslawpluta, this is not a development related issue. The data pipeline is a separate. It would be best to send an email using the the email address provided in the footer of the website.

**Comment by xenatisch** [comment]
@przemyslawpluta I reported it for you, and you're right. There was an issue in the pipeline that has now been fixed. The new data will be deployed any moment now. 

Thank you.
