### ISSUE TITLE
Make test data available in CSV/JSON

### ISSUE THREAD

**Issue by tomwhite** [PublicHealthEngland/coronavirus-dashboard#74]
Data for number of tests performed and number of people tested is only available in HTML format from https://www.gov.uk/guidance/coronavirus-covid-19-information-for-the-public#number-of-cases-and-deaths

There is also nowhere (that I know of) to download the historical data. Also, the data is subject to revisions, and there is no way of knowing which days the revisions apply to. For example, on 25 April the notes on that page said:

> The difference between the cumulative numbers from today and yesterday for people tested is 50,499 higher than the daily increase figure. Cumulative testing figures include 50,499 retrospective reports of people who tested negative between 31 January and 24 April.

But there is no way of knowing the testing dates of those 50,499 reports. 

Please consider adding the full dataset as CSV and JSON files on the dashboard.

**Comment by xenatisch** [comment]
Hi @tomwhite. I'm afraid this is not a dev-related issue. Could you please get in touch using the email provided in the footer of the website?

We add all new additions to our data pipeline onto CSV and JSON files. 

Regarding historical data; we are working to release the archives. I assume the development should be done at some point this evening, and once tested and verified, it will be deployed to the service. That will likely happen tomorrow though.

Thank you.

**Comment by tomwhite** [comment]
Hi @xenatisch. Thanks for your reply. I have sent an email as you suggested.

**Comment by Ha-san-ali** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Feature: Make test data available in CSV/JSON](https://trello.com/c/DeKQlX60/332-feature-make-test-data-available-in-csv-json)
