### ISSUE TITLE
[A11y] 1.3.1 Info and Relationships – Page Regions Not Identified with ARIA Landmarks

### ISSUE THREAD

**Issue by bsaadat** [PublicHealthEngland/coronavirus-dashboard#79]
Tester has observed that when viewing the code behind the page, regions of the page are not identified with ARIA landmarks. It is expected that page regions are identified with landmarks. A list of valid landmark roles can be seen on the following link: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles

It is recommended this is done even if HTML5 is in use, as users of older screen readers may not be able to navigate HTML5 landamarks.

This issue is specifically observed with the body of the pages under test, which should also have role="main".

This does not comply with WCAG Level A 2.1:
1.3.1 Info and Relationships - https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html 
 
**Steps to Recreate:**
1.    Navigate to URL
2.    Review HTML for usage of 'Role="main"
3.    Observe issue

**This has been observed on the following pages:**

Coronavirus (COVID-19) cases in the UK
Coronavirus (COVID-19) cases in the UK About
Coronavirus (COVID-19) cases in the UK Accessibility Statement

**Environment:**
Windows 10 – Chrome 80
 
**This issue is known to occur on:**
Believed to be global
 
**Reproduction rate:**
100% - Consistently reproducible. Occurs every time that it is attempted.
 
**Supporting material:**
Screenshot/Video

**Version:**
https://coronavirus.data.gov.uk/

**Comment by bsaadat** [comment]
![image](https://user-images.githubusercontent.com/27902577/80504202-c0a81100-896a-11ea-9629-dd9db7b0cf0f.png)

**Comment by bsaadat** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[A11y] 1.3.1 Info and Relationships – Page Regions Not Identified with ARIA Landmarks](https://trello.com/c/GV6UR1Tk/213-a11y-131-info-and-relationships-page-regions-not-identified-with-aria-landmarks)

**Comment by xenatisch** [comment]
Fixed in #143 with thanks to @richardTowers for the contribution.
