### ISSUE TITLE
Add descriptive aria-label to map so that it’s announced sensibly when focused

### ISSUE THREAD

**Issue by bsaadat** [PublicHealthEngland/coronavirus-dashboard#83]
Add descriptive aria-label to map so that it's announced sensibly when focused. At the moment, for example, if you focus the map, VoiceOver will read all of the text within it, which is ““zoom in, zoom out, leaflet, link, vertical line copyright sign, openstreetmap, link, contributors, copyright sign, carto, link, group”.

Add descriptive aria-label to map so that announcements are more concise whilst being descriptive enough for user.

**Comment by bsaadat** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add descriptive aria-label to map so that it’s announced sensibly when focused](https://trello.com/c/wbVdv79e/187-add-descriptive-aria-label-to-map-so-that-its-announced-sensibly-when-focused)

**Comment by xenatisch** [comment]
This was fixed in [release v1.5.5](https://github.com/PublicHealthEngland/coronavirus-dashboard/releases/tag/1.5.5).
