### ISSUE TITLE
Set $govuk-font-family to a different font stack before importing govuk-frontend to override the font stack

### ISSUE THREAD

**Issue by bsaadat** [PublicHealthEngland/coronavirus-dashboard#90]
Set $govuk-font-family to a different font stack before importing govuk-frontend to override the font stack

**Comment by bsaadat** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Set $govuk-font-family to a different font stack before importing govuk-frontend to override the font stack](https://trello.com/c/YKySJhhZ/195-set-govuk-font-family-to-a-different-font-stack-before-importing-govuk-frontend-to-override-the-font-stack)

**Comment by MikeCoats** [comment]
I've moved the font stack declaration from the body tag to the govuk-frontend variable, but this has shown up a couple of places where the govuk classes haven't been used on the text.

![image](https://user-images.githubusercontent.com/37802088/80608567-dbdc5480-8a2e-11ea-95d3-5ee6e9c933e2.png)

To make it more obvious, I changed the govuk font to an unreadable one,

```diff
-$govuk-font-family: "GDS Transport", Arial, sans-serif;
+$govuk-font-family: "Webdings";
```

So now, I'm going to fix any element that's still 'readable', to make sure the correct govuk classes have been applied. It looks like the `BigNumber` and `PageTitle` components are the culprits.

![image](https://user-images.githubusercontent.com/37802088/80608795-37a6dd80-8a2f-11ea-9f4f-92d7722292ff.png)

**Comment by MikeCoats** [comment]
It looks like the charts' tooltips are also 'unstyled' by this change.

![image](https://user-images.githubusercontent.com/37802088/80609178-b69c1600-8a2f-11ea-8936-19da46ed4dc7.png)

![image](https://user-images.githubusercontent.com/37802088/80609238-c61b5f00-8a2f-11ea-908a-5540f1f288c7.png)
