### ISSUE TITLE
Bug: Chart data spillage when resizing

### ISSUE THREAD

**Issue by bsaadat** [publichealthengland/coronavirus-dashboard#93]
**Summary of issue**
When resizing browser in Firefox chart data spillage

**Steps to reproduce**
Open Dashboard in firefox
Resize browser

**Expected result**
Should not spill onto other chart

**Actual result**
See screenshot

**System**
75.0 (64-bit

**Comment by bsaadat** [comment]
![image](https://user-images.githubusercontent.com/27902577/80507042-4aa5a900-896e-11ea-8576-ed6188fa48c3.png)

**Comment by bsaadat** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug: Chart data spillage when resizing](https://trello.com/c/c9xwcIA8/315-bug-chart-data-spillage-when-resizing)

**Comment by TS000** [comment]
Hello, I'm having trouble reproducing your bug. Could you please share the window dimensions that you see this bug happeneing? Thank you.
