### ISSUE TITLE
Add a "back to top" link

### ISSUE THREAD

**Issue by bsaadat** [PublicHealthEngland/coronavirus-dashboard#97]
Add a "Back to top" link, which will take the user to the top of the page rather than having to scroll back.

**Comment by bsaadat** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add a "back to top" link](https://trello.com/c/UgTu9Dh7/253-add-a-back-to-top-link)

**Comment by MikeCoats** [comment]
I had a quick look on the [Insights/Network](https://github.com/PublicHealthEngland/coronavirus-dashboard/network) page and it doesn't look like anyone's working on this yet. Mind if I take a run at it?

**Comment by Ha-san-ali** [comment]
Go for it @MikeCoats, heres an image of how it should look

![image](https://user-images.githubusercontent.com/29210115/80728200-92f3d100-8afe-11ea-8e10-eac872639ee8.png)

**Comment by xenatisch** [comment]
@MikeCoats By all means. I didn't know the ticket was here and was about to start working on it for the about page. I'd be grateful if you take over though.

**Comment by MikeCoats** [comment]
@Ha-san-ali @xenatisch 

Cheers, folks.

I've seen that back-to-top's been discussed on the [Design System backlog](https://github.com/alphagov/govuk-design-system-backlog/issues/5) with examples given from
- [the design system itself](https://design-system.service.gov.uk/components/accordion/)
- [and the accessibility-requirements page](https://www.gov.uk/guidance/accessibility-requirements-for-public-sector-websites-and-apps)

Your screenshot suggests an approach similar to the design system's one. Their link's position is dependent on them having a left hand navigation section, as when we resize the dashboard window, we'll lose our left margin - particularly at mobile resolutions. The accessibility-requirements page has the link appear over the top of the content when it's visible.

Do you think a mix of both approaches might work? Style the link as per your screenshot and the design system, but place it on an overlaying block like the accessibility-requirements page?

**Comment by Ha-san-ali** [comment]
@MikeCoats I think the approach you described sounds like a good idea. I will defer to @xenatisch on implementation advice

**Comment by xenatisch** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add a "back to top" link](https://trello.com/c/UgTu9Dh7/253-add-a-back-to-top-link)
